version: '3.8'
services:
  backend_fastapi_2024:
    image: ckala62rus/fastapi_architecture_2024
    container_name: backend_fastapi_2024
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
#    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
#    tty: true
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "backend_log"
    deploy:
      resources:
        limits:
          memory: 512M
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./docker/minio_data:/data
      - ./docker/minio_backup:/tmp/backup
    ports:
      - "127.0.0.1:9000:9000"
      - "9001:9001"

  nginx_minio:
    image: nginx:1.19.2-alpine
    container_name: nginx_minio
    volumes:
      - ./docker/nginx-minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "88:88"
    depends_on:
      - minio

  db:
    container_name: db_fastapi_2024
    image: postgres:14.1-alpine
#    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/backup/postgres:/tmp/backup
    env_file:
      - ./backend/.env
    deploy:
      resources:
        limits:
          memory: 512M

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_fastapi_2024
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M

  fba_redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    container_name: fba_redis
#    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - fba_redis:/var/lib/redis

  celery_monitor:
    container_name: celery_monitor
    image: ckala62rus/celery_monitor_fastapi_architecture_2024
    build:
      context: .
      dockerfile: ./docker/celery_monitor/DockerFile
    ports:
      - "8555:8555"
    command: sh -c "celery -A task.celery flower --port=8555 --basic-auth=admin:123456"
#    restart: always
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - fba_redis
      - db
    deploy:
      resources:
        limits:
          memory: 512M

  supervisor:
    image: ckala62rus/supervisor_fastapi_architecture_2024:1.0.0
    build:
      context: .
      dockerfile: ./docker/supervisor/Dockerfile
    container_name: supervisor
    tty: true
#    command: bash -c "celery -A task.celery flower --port=8555 --basic-auth=admin:123456"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - fba_redis
      - db
    deploy:
      resources:
        limits:
          memory: 512M

  mongo:
    image: mongo
    container_name: mongo
#    restart: always
#    ports:
#      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: M0ngo100500
      TZ: Europe/Moscow
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/backup/mongo:/tmp/backup

#  maildev:
#    container_name: maildev
#    image: maildev/maildev
#    restart: always
#    environment:
#      - TZ=Asia/Shanghai
#      - MAILDEV_WEB_PORT=1080
#      - MAILDEV_SMTP_PORT=1025
#    ports:
#      - "8080:1080"
#      - "8025:1025"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1m"

volumes:
  pgdata:
    name: pgdata
  fba_redis:
    name: fba_redis
  mongo_data:
    name: mongo_data
