version: '3.8'
services:
  backend_fastapi_2024:
    image: ckala62rus/fastapi_architecture_2024
    container_name: backend_fastapi_2024
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
#    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env

  db:
    container_name: db_fastapi_2024
    image: postgres:14.1-alpine
#    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/backup/postgres:/tmp/backup
    env_file:
      - ./backend/.env

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_fastapi_2024
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  fba_redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    container_name: fba_redis
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - fba_redis:/var/lib/redis

  celery_monitor:
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
    ports:
      - "8555:8555"
    container_name: celery_monitor
    command: bash -c "celery -A task.celery flower --port=8555 --basic-auth=admin:123456"
#    restart: always
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - fba_redis
      - db

  supervisor:
    build:
      context: .
      dockerfile: ./docker/supervisor/Dockerfile
    container_name: supervisor
    tty: true
#    command: bash -c "celery -A task.celery flower --port=8555 --basic-auth=admin:123456"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - fba_redis
      - db

  mongo:
    image: mongo
    container_name: mongo
#    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: M0ngo100500
      TZ: Europe/Moscow
    volumes:
      - mongo_data:/data/db
      - ./docker/backup/mongo:/tmp/backup

volumes:
  pgdata:
    name: pgdata
  fba_redis:
    name: fba_redis
  mongo_data:
    name: mongo_data
