version: '3.8'
services:
  backend_fastapi_2024:
    container_name: backend_fastapi_2024
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
#    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  db:
    container_name: db_fastapi_2024
    image: postgres:14.1-alpine
#    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_fastapi_2024
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
