version: '3.8'
services:
  backend_fastapi_2024:
    container_name: backend_fastapi_2024
    build:
      context: .
      dockerfile: ./docker/fastapi/DockerFile
#    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
