name: Build and Publish Docker Images

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry ( fastapi_architecture_2024 )
        uses: docker/build-push-action@v4
        with:
          file: ./docker/fastapi/DockerFile
          push: true
          tags: ckala62rus/fastapi_architecture_2024:latest

      - name: Publish to Registry ( celery_monitor_fastapi_architecture_2024 )
        uses: docker/build-push-action@v4
        with:
          file: ./docker/celery_monitor/DockerFile
          push: true
          tags: ckala62rus/celery_monitor_fastapi_architecture_2024:latest

  build_supervisor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish to Registry ( supervisor_fastapi_architecture_2024 )
        uses: docker/build-push-action@v4
        with:
          file: ./docker/supervisor/Dockerfile
          push: true
          tags: ckala62rus/supervisor_fastapi_architecture_2024
